### ISSUE TITLE
[Core] investigate HZ 3.9

### ISSUE THREAD

**Issue by dsukhoroslov** [dsukhoroslov/bagri#122]
- memory consumption inreased in comparison with HZ 3.8.6
- fix for BaseIndexStore is still not ported to HZ 3.9

**Comment by pveentjer** [comment]
Can you give some more information about the memory consumption? So which data-structure, e.g. IMap? What was the configuration? What type of key/values and how many? What was the old and what is the new memory consumption?

**Comment by dsukhoroslov** [comment]
Hi @pveentjer,
see the heap screens below. I just start cache server, no data in it yet. This one for HZ 3.8.7:

![hz_3 8 7](https://user-images.githubusercontent.com/5073945/32821818-818ab428-c9e6-11e7-8b2d-f1b809b227af.png)

This one for HZ 3.9:

![hz_3 9](https://user-images.githubusercontent.com/5073945/32821843-b34a9f1e-c9e6-11e7-924f-2d373512275b.png)

The drops in consumption above caused by manual GC. We see significant increase in memory consumption on empty server, right? When server is loaded with data (just 20000 documents, for tests) then it looks ok:

![hz_3 8 7_20000](https://user-images.githubusercontent.com/5073945/32821980-5bb5ea0a-c9e7-11e7-953a-528b257377eb.png)

![hz_3 9_20000](https://user-images.githubusercontent.com/5073945/32821991-6853faf4-c9e7-11e7-824b-ed39ef96f545.png)

**Comment by dsukhoroslov** [comment]
moving to HZ 3.9.3 in Bagri 1.2.1 in order to improve range queries
