### ISSUE TITLE
[Management] Admin server deployed on Linux cannot be connected through jmx console

### ISSUE THREAD

**Issue by svetlanatrue** [dsukhoroslov/bagri#15]
Steps to reproduce:
1. Connect to remote pc and start bgadmin.sh from putty on any profile. 
2. Use command: ps -ef|grep java and find needed port for connection to visualVM (jmx connection).

Expected result:
bgadmin can be added through jmx connection and appears in visualVM.

Actual result:
bgadmin cannot be added through jmx connection.

The same scenario works properly on Windows platform

**Comment by dsukhoroslov** [comment]
configuration issue, resolved. the -Djava.rmi.server.hostname java option must be properly set in bgadmin.conf file.
